from setuptools import setup, find_packages

setup(
    name="urban-planner-backend",
    version="1.0.0",
    description="Backend for Generative Urban City Planner with GNN optimization",
    author="Urban Planning Team",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn[standard]>=0.24.0",
        "pydantic>=2.5.0",
        "torch>=2.1.0",
        "torch-geometric>=2.4.0",
        "geopandas>=0.14.1",
        "shapely>=2.0.2",
        "rasterio>=1.3.9",
        "numpy>=1.24.3",
        "pandas>=2.1.3",
        "scikit-learn>=1.3.2",
        "matplotlib>=3.8.2",
        "folium>=0.15.0",
        "python-multipart>=0.0.6",
        "python-dotenv>=1.0.0",
        "sqlalchemy>=2.0.23",
        "alembic>=1.13.0",
        "psycopg2-binary>=2.9.9",
        "redis>=5.0.1",
        "celery>=5.3.4",
        "networkx>=3.2.1",
        "osmnx>=1.7.1",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "mypy>=1.5.0",
            "flake8>=6.0.0",
        ],
        "gpu": [
            "torch>=2.1.0+cu118",
            "torch-geometric>=2.4.0",
        ]
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)